name: "Run CI checks"
on: [push]

jobs:
    bun-test:
        runs-on: ubuntu-22.04
        name: "Run tests on Bun"
        steps:
            - uses: actions/checkout@v4
            - uses: oven-sh/setup-bun@v2
              with:
                bun-version: latest
            - run: bun install
            - run: bun test

    node-test:
        runs-on: ubuntu-22.04
        name: "Run tests on Node"
        strategy:
            matrix:
                node-version: [18, 20, 22, 24]
        steps:
            - uses: actions/checkout@v4
            - uses: actions/setup-node@v4
              with:
                node-version: ${{ matrix.node-version }}
            - run: npm install
            - run: npm test

    prettier:
        runs-on: ubuntu-22.04
        name: "Run prettier"
        steps:
            - uses: actions/checkout@v4
            - uses: oven-sh/setup-bun@v2
              with:
                bun-version: latest
            - run: bun install
            - run: bun format
